# Generated by Django 3.2.6 on 2021-09-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_orderitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='data_ordered',
            field=models.DateTimeField(),
        ),
    ]
