# Generated by Django 3.2.6 on 2021-09-13 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_product_amout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('data_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('growth_revenue', models.FloatField(default=0.0, null=True)),
                ('growth_cost', models.FloatField(default=0.0, null=True)),
                ('growth_profit', models.FloatField(default=0.0, null=True)),
                ('growth_total_revenue', models.FloatField(default=0.0, null=True)),
                ('growth_total_cost', models.FloatField(default=0.0, null=True)),
                ('growth_total_profit', models.FloatField(default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=30.0, max_digits=8, null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
