# Generated by Django 3.2.6 on 2021-09-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
    ]
