# Generated by Django 3.2.6 on 2021-09-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justAdmin', '0002_auto_20210913_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='data_create',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
