# Generated by Django 3.2.6 on 2021-09-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticalUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amout', models.IntegerField()),
                ('data_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
