# Generated by Django 3.2.6 on 2021-09-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_loginattempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginattempts',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
