# Generated by Django 3.2.6 on 2021-09-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amout',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
