# Generated by Django 3.2.6 on 2021-09-23 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_amout'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
